import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useQuery } from "@apollo/client";
import { GET_POKEMON } from "../graphQl/query";

export default function Home() {
  // const variables = {
  //   limit: 12,
  //   offset: 0,
  // };

  // const { data, error, loading } = useQuery(pokemons, {
  //   variables,
  // });

  const variables = {
    name: "bulbasaur",
  };

  const { data, error, loading } = useQuery(GET_POKEMON, {
    variables,
  });

  if (error) {
    console.log(error);
  }

  if (loading) {
    console.log("loading");
  }

  if (data) {
    console.log(data);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline text-red-500">
        Hello world!
      </h1>
    </div>
  );
}
