import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useQuery, gql } from "@apollo/client";

const pokemons = gql`
  query pokemons($limit: Int, $offset: Int) {
    pokemons(limit: $limit, offset: $offset) {
      next
      previous
      message
      results {
        id
        url
        name
        image
      }
    }
  }
`;

const pokemon = gql`
  query pokemon($name: String!) {
    pokemon(name: $name) {
      id
      name
      sprites {
        front_default
      }
      moves {
        move {
          name
        }
      }
      types {
        type {
          name
        }
      }
    }
  }
`;

export default function Home() {
  // const variables = {
  //   limit: 12,
  //   offset: 0,
  // };

  // const { data, error, loading } = useQuery(pokemons, {
  //   variables,
  // });

  const variables = {
    name: "bulbasaur",
  };

  const { data, error, loading } = useQuery(pokemon, {
    variables,
  });

  if (error) {
    console.log(error);
  }

  if (loading) {
    console.log("loading");
  }

  if (data) {
    console.log(data);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline text-red-500">
        Hello world!
      </h1>
    </div>
  );
}
